#!/bin/bash


STARTRUN=0
ENDRUN=30

STARTEXP=1
ENDEXP=6


for (( e=STARTEXP; e<=ENDEXP; e++))
do
  for (( c=STARTRUN; c<ENDRUN; c++))
  do
    echo "experiment=$e -> run_numer=$c"
    python run_experiments_multiDim.py --run_num $c --exp_num $e
  done
done